pur_beurre/pur_beurre/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
# from django.contrib.auth import views as auth_views


from substitute import views

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^substitute/', include(('substitute.urls','substitute'), namespace="substitute")),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
	import debug_toolbar
	urlpatterns = [
		url(r'^__debug__/', include(debug_toolbar.urls)),
	] + urlpatterns

pur_beurre/substitute/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name="index"),
    url(r'^legal/$', views.legal, name="legal"),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^sign_in/$', views.sign_in, name='sign_in'),
    url(r'^account/$', views.user_account, name='account'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.product_sheet, name='product_sheet'),
    url(r'^search/$', views.search, name='search'),
    url(r'^find_substitute/(?P<product_id>[0-9]+)/$', views.find_substitute, name='find_substitute'),
    url(r'^favorites/$', views.favorites, name='favorites'),
    url(r'^add_favorite/(?P<product_id>[0-9]+)/$', views.add_favorite, name='add_favorite'),

]

pur_beurre/substitute/models.py
"""Models used for the application"""
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    """Model use to stock products"""
    name = models.CharField(max_length=200)
    image_url = models.URLField()
    image_small_url = models.URLField()
    categories = models.CharField(max_length=500)
    score = models.CharField(max_length=5)
    nutriments = models.CharField(max_length=1500)
    code = models.CharField(max_length=30)

class Favorite(models.Model):
    """Model used to stock the favorites products of an user"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

pur_beurre/substitute/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label="Nom d'utilisateur", max_length=30)
	password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)


class SignInForm(forms.Form):
	username = forms.CharField(label="Nom d'utilisateur", max_length=30)
	email = forms.EmailField(label="E-mail")	
	password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)
	confirm_password = forms.CharField(label="Confirmer mot de passe", widget=forms.PasswordInput)

pur_beurre/substitute/views.py
import json

from django.shortcuts import render, redirect
# from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse

from .forms import LoginForm, SignInForm
from .models import Product, Favorite
from substitute import utils

#Globales variables used for the pagination of search results
PRODUCTS_LIST = ''
USER_QUERY = ''

def index(request):
    """Display the main page of the application"""
    return render(request, 'substitute/index.html')

def legal(request):
    """Display legal notice"""
    return render(request, 'substitute/legal.html')

def user_login(request):
    """View used to login"""

    #Use to store the error message in case of error
    error = False

    #If POST request, try to connect the user
    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
            else:
                error = True
    #If not POST request display the form to login
    else:
        form = LoginForm()

    return render(request, 'substitute/login.html', locals())


def user_logout(request):
    """View used to logout the user"""
    logout(request)
    return redirect(reverse(index))

def sign_in(request):
    """View to sign-in"""

    #Use to store the error message in case of error
    error = False

    #If POST request, try to create a new user with the informations.
    if request.method == "POST":
        form = SignInForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']

            if password != confirm_password:
                error = "Les deux mots de passe ne sont pas identiques ! "
            else:
                user = User.objects.create_user(username, email, password)
                user.save()
                confirmation_message = 'Le compte a bien été créé. Merci pour votre inscription !'
                #Log the new user after create his account
                login(request, user)

    #If not POST request, display the form
    else:
        form = SignInForm()

    return render(request, 'substitute/sign_in.html', locals())


def user_account(request):
    """Display the name and the email of the user"""
    return render(request, 'substitute/account.html', locals())

def product_sheet(request, product_id):
    """View to display the selected product"""
    product_to_display = Product.objects.get(pk=product_id)
    product_to_display.nutriments = json.loads(product_to_display.nutriments.replace('\'', '"'))
    score_image = 'substitute/img/nutriscore-' + product_to_display.score + '.svg'

    return render(request, 'substitute/product_sheet.html', locals())

def search(request):
    """View that manage the search function"""

    no_result_message = False
    no_query_message = False

    #Use global variables to store the query and the result of the search 
    #Those gobal variables are usefull because of the pagination
    global PRODUCTS_LIST
    global USER_QUERY

    if request.method == "POST":
        query = request.POST.get('query')

        if not query:
            #If the user don't write a product name, display all the products
            PRODUCTS_LIST = Product.objects.all().order_by('name')
            query = "" #Use to not display 'None' in the title of the result page
            no_query_message = True
        else:
            #Search products with an name containing the query
            PRODUCTS_LIST = Product.objects.filter(name__icontains=query).order_by('name')
            USER_QUERY = query

            if not PRODUCTS_LIST:
            #If no result, display all the products
                no_result_message = 'Désolé, il n\'y a pas de résultats pour votre recherche...'
                PRODUCTS_LIST = Product.objects.all().order_by('name')


    paginator = Paginator(PRODUCTS_LIST, 30)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    context = {
        'products':products,
        'query':USER_QUERY,
        'no_result_message':no_result_message,
        'no_query_message':no_query_message,
        'paginate':True
    }

    return render(request, 'substitute/search_result.html', context)

def find_substitute(request, product_id):
    """View that display the selected product and the substitutes associate"""
    product_selected = Product.objects.get(pk=product_id)
    score_image = 'substitute/img/nutriscore-' + product_selected.score + '.svg'
    substitute_query = utils.find_substitute(product_id)
    list_substitute = []
    #Create a list of product object to display in the template
    for product in substitute_query:
        list_substitute.append(Product.objects.get(pk=product.id))

    if list_substitute == []:
        no_substitute = "Désolé, il n'y a pas de substitut pour ce produit dans notre base de données... "

    return render(request, 'substitute/substitutes_found.html', locals())

@login_required
def add_favorite(request, product_id):
    """Add the product selected in the list of favorite of the user"""
    query = product_id
    result_message = ""
    if query:
        try:
            Favorite.objects.get(user_id=request.user.id, product_id=int(query))
            result_message = "Ce produit est déjà dans vos favoris."
        except ObjectDoesNotExist:
            new_favorite = Favorite.objects.create(user_id=request.user.id, product_id=int(query))
            new_favorite.save()
            result_message = "Le produit a bien été enregistré."

    return HttpResponse(result_message)

@login_required
def favorites(request):
    """View that display all the favorites of the user"""
    favorites_query = utils.find_favorites(request.user)
    favorites_list = []
    for favorite in favorites_query:
        favorites_list.append(Product.objects.get(pk=favorite.product.id))

    return render(request, 'substitute/favorites.html', locals())

pur_beurre/substitute/templates/substitute/account.html
{% extends 'substitute/base.html' %}

{% block content %}
<section id="account_info">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h1>Profil</h1>
        <p><strong>Nom :</strong> {{ user.username }}</p>
        <p><strong>Email :</strong> {{ user.email }}</p>
      </div>  
   </div>
  </div>
</section>

{% endblock %}

pur_beurre/substitute/templates/substitute/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pur Beurre - Du gras, oui, mais de qualité </title>

    {% load static %}

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'substitute/img/favicon.png' %}" />

    <!-- Bootstrap core CSS -->
    <link href="{% static 'substitute/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'substitute/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link href="http://fonts.googleapis.com/css?family=Scope+One" rel="stylesheet" type="text/css">

    <!-- Plugin CSS -->
    <link href="{% static 'substitute/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'substitute/css/creative.css' %}" rel="stylesheet">

    <!-- Call Jquery framework -->  
    <script src="{% static 'substitute/vendor/jquery/jquery.min.js' %}"></script>

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a href="/"><img src="{% static 'substitute/img/logo_mini.png' %}" id="logo"></a>
        <a class="navbar-brand js-scroll-trigger" href="/">Pur Beurre</a>
        <div class="navbar-collapse" id="navbarResponsive">
          {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'substitute:account' %}">Mon compte</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'substitute:favorites'%}">Mes aliments</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'substitute:logout' %}">Deconnexion</a>
            </li>
          </ul>
          {% else%}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'substitute:login' %}">Se connecter</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'substitute:sign_in' %}">S'inscrire</a>
            </li>
          </ul>
          {% endif%}
        </div>
      </div>
    </nav>

    <div id="container">
    {% block content %}{% endblock %}
    </div>
    
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <p>
              <a href="{% url 'substitute:legal' %}">Mentions legales</a>
            </p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <p>
              <a href="{% url 'substitute:index' %}#contact">Contact</a>
            </p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'substitute/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'substitute/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'substitute/vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'substitute/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'substitute/js/creative.min.js' %}"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

pur_beurre/substitute/templates/substitute/favorites.html
{% extends 'substitute/base.html' %}

{% block content %}
<section id="account_info">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h1 id="product_title">Produits favoris de {{ user.username}}</h1>
      </div>
    </div>
    <div class="row">
      	{% for favorite in favorites_list %}
        	<div class="col-lg-5 text-center mx-auto">
        		<p><a href="{% url 'substitute:product_sheet' product_id=favorite.id%}">{{favorite.name}}</a></p>
        		<img src="{{ favorite.image_small_url }}" alt="{{ favorite.name }}">
        	</div>  
        {% endfor %}
	</div>
   </div>
</section>

{% endblock %}

pur_beurre/substitute/templates/substitute/index.html
{% extends 'substitute/base.html' %}

{% load static %}

{% block content %}
      <header class="masthead text-center text-white">
        <div class="container my-auto">
          <div class="row">
            <div class="col-lg-10 mx-auto header-title">
              <h1 class="text-uppercase">
                <span class="catchword"><strong>Du gras oui, mais de qualité !<strong> </span>
              </h1>
              <hr>
                <h2><span class="catchword">Trouvez un produit de substitution à ceux que vous consommez tous les jours.</span></h2>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-10 mx-auto form-search-substitute">
              <form method="post" action="{% url 'substitute:search' %}">
                {% csrf_token %}
                <input class="col-lg-8" type="text" name="query"  id="search-zone" placeholder="Saisissez un produit">
                <input class="col-lg-2" type="submit" value="Chercher" id="button">
            </form>
            </div>
          </div>
        </div>
      </header>

      <section id="authors">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto text-center">
              <h2 class="section-heading">Colette et Remy</h2>
              <hr class="my-4">
              <p class="mb-5">Remy et Colette sont amoureux de la gastronomie française (on ne peut les blâmer !). 
                Travaillant quotidiennement avec les meilleurs produits du terroir, ils affectionnent 
                particulièrement la bonne chaire et aiment partager leur passion.
              </p>
            </div>  
          </div>
          <div class="row">
            <div class="col-lg-5 col-md-6 text-center">
                <img src="{% static 'substitute/img/colette.png' %}">
                <h3 class="mb-3">Colette</h3>
                <p class="text-muted mb-0">Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !
                </p>
            </div>
            <div class="col-lg-2">
              
            </div>
            <div class="col-lg-5 col-md-6 text-center">
                <img src="{% static 'substitute/img/remy.jpg' %}">
                <h3 class="mb-3">Remy</h3>
                <p class="text-muted mb-0">Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !
                </p>
            </div>
          </div>
        </div>
      </section>

      <section id="contact">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 mx-auto text-center">
              <h2 class="section-heading">Contactez-nous ! </h2>
              <hr class="my-4">
              <p class="mb-5">Nous sommes preneur de toutes vos remarques pour améliorer notre projet :)</p>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-4 ml-auto text-center">
              <i class="fa fa-phone fa-3x mb-3 sr-contact"></i>
              <p>123-456-6789</p>
            </div>
            <div class="col-lg-4 mr-auto text-center">
              <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
              <p>
                <a href="mailto:your-email@your-domain.com">colette&remy@purbeurre.com</a>
              </p>
            </div>
          </div>
        </div>
      </section>

{% endblock%}

pur_beurre/substitute/templates/substitute/legal.html
{% extends 'substitute/base.html' %}

{% block content %}

<section id="legal">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h2 >Mentions légales</h2>
        <p class="mb-5">
        	<p>La société <strong>PUR BEURRE</strong> a pour activité principale la conception d'applications liées à l'alimentation.</p>
        	<p>PUR BEURRE est une société par actions simplifiée au capital de 12.000 euros, dont le siège social est situé 4, rue de la Croissant, 75000 Paris et immaticulé au Registre du Commerce et des Sociétés de Paris sous le numéro 123 456 789</p>
        	<address>4 rue du Croissant - 75000 PARIS - FRANCE</address>
        	<p><em>Téléphone</em> : +332.12.34.56.78</p>
        	<p><em>Courrier électronique</em> : contact@purbeurre.com</p>
        	<p><em>N° de TVA intracommunautaire</em> : FR76 123 456 789</p>
        	<p><em>Hébergeur du Site Internet</em> : <adress>SALESFORCE, The Landmark @ 1 Market St., Suite 300 San Francisco, CA, 94105</adress></p>
        	<p><em>Conception</em> : Ronan LE HAY. <br/></p>
          <p><em>Thème utilisé : </em><a href="https://blackrockdigital.github.io/startbootstrap-creative/">Startbootstrap-creative</a></p>
          <p>Images et icônes mise à disposition gratuitement par IconMoon.</p>
        </p>
      </div>  
   </div>
  </div>
</section> 
{% endblock %}

pur_beurre/substitute/templates/substitute/login.html
{% extends 'substitute/base.html' %}

{% block content %}

<section id="login">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h1 class="section-heading">Se connecter</h1>

          {% if error %}
          <p><strong>Utilisateur inconnu ou mauvais de mot de passe.</strong></p>
          {% endif %}

          {% if user.is_authenticated %}
          {% load static %}
          <p>Vous êtes connecté, {{ user.username }} !</p>
          <p> Vous allez être redirigé vers la page d'accueil dans <span id='counter'>5</span> seconde(s).</p>
          <p>Si ce n'est pas le cas, cliquer <a href="{% url 'substitute:index' %}">ici</a></p>
          <script type="text/javascript" src="{% static 'substitute/js/counter.js' %}"></script>
          {% else %}
          <div class="form_div">
            <form method="post" action="{% url 'substitute:login' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Se connecter" />
            </form>
          </div>
          {% endif %}
      </div>  
   </div>
  </div>
</section>

{% endblock %}

pur_beurre/substitute/templates/substitute/product_sheet.html
{% extends 'substitute/base.html' %}

{% block content %}
<section id="account_info">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h1 id="product_title">{{ product_to_display.name }}</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        {% load static %}
        <img src="{% static score_image %}" alt="{{product_to_display.score}}">
        <img src="{{ product_to_display.image_url }}" alt="Photo du produit : {{ product_to_display.name }}"/>  
      </div>
      <div class="col-lg-8">
        <table class="table table-striped table-bordered nutriments-table">
          <tr>
            <th>Nutriment</th>
            <th>Valeur</th>
          </tr>
          {% for key, value in product_to_display.nutriments.items %}
            {% if '100' in key %}
            <tr>
              <td>{{ key }}</td>
              <td>{{ value }}</td>
            </tr>
            {% endif %}
          {% endfor %}
        </table>
      </div>
    </div>

    <div class="row">
      <div class="mx-auto">
        <p><a href="https://fr.openfoodfacts.org/produit/{{product_to_display.code}}/">Voir la fiche complète sur OpenFoodFacts</a></p>  
      </div>
    </div>
  </div>
</section>

{% endblock %}

pur_beurre/substitute/templates/substitute/search_result.html
{% extends 'substitute/base.html' %}

{% block content %}
<section id="list_result">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h1>Résultat de la recherche : {{ query }}</h1>
        {% if no_result_message %}
        <p>{{ no_result_message }}</p>
        <p>Voici la liste de tous les produits : </p>
          {% for result in products  %}
            <li class="list-unstyled"><a href="{% url 'substitute:find_substitute' product_id=result.id %}">{{ result.name }}</a></li>
          {% endfor %}
        {% elif no_query_message %}
        <p>Vous n'avez rien entré dans le champ de recherche.</br>
        Voici la liste des produits : </p>
        {% endif %}
        <ul>
        	{% for result in products  %}
        	<li class="list-unstyled"><a href="{% url 'substitute:find_substitute' product_id=result.id %}">{{ result.name }}</a></li>
        	{% endfor %}
       </ul>
      </div>  
   </div>
  </div>
  {% load static%}
  {% if paginate %}
    <p class="text-center">
      {% if products.has_previous %}
          <a href="?page={{ products.previous_page_number }}"><img src="{% static 'substitute/img/mini_left_arrow.png' %}" alt="Précédent"></a>
      {% endif %}
      {% if products.has_next %}
          <a href="?page={{ products.next_page_number }}"><img src="{% static 'substitute/img/mini_right_arrow.png' %}" alt="Suivant"></a>
      {% endif %}
    </p>
  {% endif %}
</section>

{% endblock %}

pur_beurre/substitute/templates/substitute/sign_in.html
{% extends 'substitute/base.html' %}

{% block content %}

<section id="signin">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h1>Inscription</h1>
        {% if error %}
          <p><strong>{{ error }}</strong></p>
        {% endif %}
        {% if confirmation_message %}
          <p><strong>{{ confirmation_message }}</strong></p>
        {% load static %}
        <p> Vous allez être redirigé vers la page d'accueil dans <span id='counter'>5</span> seconde(s).</p>
        <p>Si ce n'est pas le cas, cliquer <a href="{% url 'substitute:index' %}">ici</a></p>
        <script type="text/javascript" src="{% static 'substitute/js/counter.js' %}"></script>
        {% else %}
        <div class="form_div">
          <form method="post" action="{% url 'substitute:sign_in' %}">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Envoyer" />
          </form>
        </div>
        {% endif %}
      </div>  
   </div>
  </div>
</section>
{% endblock %}

pur_beurre/substitute/templates/substitute/substitutes_found.html
{% extends 'substitute/base.html' %}

{% block content %}

<section id="account_info">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <h1 id="product_title"><a href="{% url 'substitute:product_sheet' product_id=product_selected.id %}">{{ product_selected.name }}</a></h1>
        {% load static %}
        <img src="{% static score_image %}" alt="{{product_to_display.score}}">
        <img src="{{ product_selected.image_url }}" alt="Photo du produit : {{ product_selected.name }}"/>
      </div>  
      <h2>Vous pourriez remplacer ce produit par le(s) suivant(s) : </h2>
   </div>
   {% if no_substitute %}
   <div class="row">
    <div class="col-lg-8 mx-auto text-center">
     <p>{{ no_substitute }}</p>
    </div>
   </div>
   {% else %}
    <div class="row">
      {% for substitute in list_substitute %}
      <div class="col-lg-4 text-center">
        <h3><a href="{% url 'substitute:product_sheet' product_id=substitute.id %}">{{ substitute.name }}</a></h3>
        <p class="text-uppercase">Nutri-Score : <strong>{{substitute.score}}</strong></p>
        <img src="{{ substitute.image_small_url }}" alt="{{ substitute.name }}">
        {% if user.is_authenticated %}
        <div class="save-result" id="{{substitute.id}}"></div>
        <form method="post" action="{% url 'substitute:add_favorite' product_id=substitute.id %}">
            {% csrf_token %}
            <input type="submit" value="Sauvegarder" id="{{substitute.id}}">
        </form>
        {% endif %}
      </div>        
      {% endfor %}  
    </div>
  {% endif %}
  </div>
</section>

  
{% endblock %}

{% block javascript %}
  {% load static %}
  <script type="text/javascript" src="{% static 'substitute/js/checkbox.js' %}"></script>

{% endblock %}